import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { twoFactor } from "better-auth/plugins";

import { getDatabase } from "@/db/client.server";
import { account, session, twoFactor as twoFactorTable, user, verification } from "@/db/schema";

// Ids are always supplied by this codebase's own account-creation path
// (src/repositories/auth-credential.repository.server.ts), never generated by
// better-auth itself — generateId: false leaves session/verification rows'
// ids to each table's DEFAULT gen_random_uuid() in
// supabase/migrations/20260827130000_better_auth_core.sql instead.
export const auth = betterAuth({
  database: drizzleAdapter(getDatabase(), {
    provider: "pg",
    schema: { user, session, account, verification, twoFactor: twoFactorTable },
  }),
  emailAndPassword: { enabled: true },
  plugins: [twoFactor()],
  secret: process.env.BETTER_AUTH_SECRET,
  advanced: { database: { generateId: false } },
});
