// AUTO-GENERATED by tools/gen_types.py - do not edit by hand.
// Mirrors the Add Property form exactly.

export interface Basics {
  /** Project / property name only, e.g. 'Ikebana'. Exclude the builder name and words like 'Residences'/'Phase' unless part of the brand. */
  property_name: string | null;
  /** Builder / developer group name, e.g. 'Gala'. Usually on the cover or the 'about the developer' page. */
  developer: string | null;
  /** One of: Apartment, Villa, Penthouse, Plot, Row House, Commercial, Mixed Use. */
  category: string | null;
  /** Construction/sales status, e.g. 'Under Construction', 'Near Possession', 'Ready to Move In', 'New Launch'. */
  status: string | null;
  /** Possession timeline as printed, e.g. 'Dec 2026', '9 Months', 'RTMI'. */
  possession: string | null;
  /** Date the possession claim is dated in the document, dd-mm-yyyy. Use the brochure/RERA print date if given. Null if absent. */
  possession_confirmed_as_of: string | null;
  /** Locality / road, e.g. 'Sindhu Bhavan Road'. Not the full postal address. */
  location: string | null;
  /** City, e.g. 'Ahmedabad'. */
  city: string | null;
  /** State, e.g. 'Gujarat'. */
  state: string | null;
  /** Short marketing line printed under the project name on the cover. Max ~12 words. */
  tagline: string | null;
  /** 2-3 neutral factual sentences summarising the project for a buyer. Write it yourself from the brochure facts; no hype adjectives. */
  expert_note: string | null;
}

export interface ProjectStructure {
  /** Total land / plot area with unit, e.g. '5400 sq ft', '2.4 acres'. */
  plot_size: string | null;
  /** Configurations offered, each as its own item: ['4 BHK', '5 BHK', 'Penthouse']. */
  available_bhk_types: string[];
  /** Number of towers/blocks. */
  total_towers: number | null;
  /** Floors above ground in the tallest tower. Exclude basements/podium. */
  total_floors: number | null;
  /** Flats per floor per tower. */
  units_per_floor: number | null;
  /** Total units in the project. */
  total_units: number | null;
}

export interface ReraApprovals {
  /** RERA registration number exactly as printed, e.g. 'PR/GJ/AHMEDABAD/AHMEDABAD CITY/AUDA/RAA12345/EX1'. */
  rera_id: string | null;
  /** RERA portal URL if printed, e.g. https://gujrera.gujarat.gov.in/... */
  rera_link: string | null;
  /** Project start date per RERA, e.g. 'Jan 2025'. */
  proposed_start_date: string | null;
}

export interface ConstructionAmenities {
  /** Number of parking levels/basements. */
  parking_levels: number | null;
  /** e.g. '2-Level Podium', 'No podium'. */
  podium_structure: string | null;
  /** Lifts per tower including service lift if stated. */
  lifts_per_tower: number | null;
  /** e.g. '70% Open Area'. */
  open_space: string | null;
  /** Water heating provision, e.g. 'Yes - instant geyser', 'Central heat pump'. */
  geyser_heat_pump: string | null;
  /** AC provision, e.g. 'Yes, VRV in all bedrooms', 'Provision only'. */
  vrv_ac: string | null;
  /** e.g. 'Double-glazed soundproof', 'Single glazed aluminium'. */
  window_glasses: string | null;
  /** Brands from the specification sheet, e.g. 'Kohler, Jaquar'. */
  bath_sanitary_fittings: string | null;
  /** e.g. 'Italian marble in living, vitrified in bedrooms'. */
  flooring: string | null;
  /** Units per acre. Compute from total_units / plot area in acres only if both are printed, else null. */
  density_units_per_acre: number | null;
  /** Structure spec, e.g. 'RCC framed structure, seismic zone III compliant'. */
  construction_quality: string | null;
  /** e.g. '10 ft', '3.2 m'. */
  internal_ceiling_height: string | null;
  /** e.g. '15,000 sq ft'. */
  clubhouse_size: string | null;
}

export interface DeveloperInfo {
  /** Years the developer has been operating. */
  experience_years: number | null;
  /** Completed projects count. */
  total_delivered_projects: number | null;
  /** Currently under-construction projects count. */
  ongoing_projects: number | null;
  /** 2-3 sentences about the developer from the 'about us' section. */
  background: string | null;
  /** Named past projects, one per item, e.g. ['Godrej Garden City']. */
  notable_delivered_projects: string[];
}

export interface ConfigurationVariant {
  bhk_type: string | null;
  variant_name: string | null;
  carpet_area: string | null;
  built_up_area: string | null;
  super_built_up_area: string | null;
  bathrooms: number | null;
  balconies: number | null;
  servant_room: string | null;
  price: string | null;
  price_per_sqft: string | null;
  floor_plan_page: number | null;
}

export interface ExtractedImage {
  file_name: string;
  path: string;
  url?: string;
  source_file: string;
  page: number;
  quality?: number;
}

export interface PropertyImages {
  cover: ExtractedImage | null;
  living_room: ExtractedImage | null;
  master_bedroom: ExtractedImage | null;
  pool: ExtractedImage | null;
  clubhouse: ExtractedImage | null;
}

export interface PropertyRecord {
  basics: Basics;
  project_structure: ProjectStructure;
  rera_approvals: ReraApprovals;
  construction_amenities: ConstructionAmenities;
  developer_info: DeveloperInfo;
  configurations: ConfigurationVariant[];
  amenities: string[];
  highlights: string[];
  images: PropertyImages;
}

export interface FieldMeta {
  confidence: number; // 0-1, from the model's own evidence row
  source: { file: string; page: number | null };
  snippet: string | null; // verbatim text that justified the value
  agreement: number; // how many chunks/files agreed
  alternatives: Array<{
    value: unknown;
    confidence: number;
    source: { file: string; page: number | null };
  }>;
}

export interface Conflict {
  field: string; // dotted path e.g. 'project_structure.total_floors'
  chosen: unknown;
  rejected: Array<{
    value: unknown;
    confidence: number;
    source: { file: string; page: number | null };
  }>;
}

export interface ExtractionResult {
  property: PropertyRecord;
  form_payload: Record<string, unknown>; // flat, keys match the form inputs 1:1
  field_meta: Record<string, FieldMeta>;
  conflicts: Conflict[];
  needs_review: string[]; // fields under MIN_CONFIDENCE - highlight these
  missing_required: string[];
  image_pool: ExtractedImage[]; // everything not auto-assigned to a slot
  source_files: string[];
  completeness: {
    fields_filled: number;
    fields_total: number;
    percent: number;
    configurations_found: number;
    amenities_found: number;
  };
  meta: {
    files: Array<{
      file: string;
      pages: number;
      scanned_pages: number;
      document_kind: string;
      seconds: number;
    }>;
    model: string;
    chunks: number;
    seconds: number;
  };
}
