"""Regenerate types/property.d.ts from schema.py.  python tools/gen_types.py"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from brochure_extractor.schema import CONFIG_FIELDS, FORM, IMAGE_SLOTS, LIST_SECTIONS  # noqa: E402


def ts_type(spec: dict) -> str:
    if spec["type"] == "string[]":
        return "string[]"
    return ("number" if spec["type"] == "integer" else "string") + " | null"


def main() -> None:
    lines = [
        "// AUTO-GENERATED by tools/gen_types.py - do not edit by hand.",
        "// Mirrors the Add Property form exactly.",
        "",
    ]

    for section, fields in FORM.items():
        name = "".join(part.capitalize() for part in section.split("_"))
        lines.append(f"export interface {name} {{")
        for spec in fields:
            lines.append(f"  /** {spec['desc']} */")
            lines.append(f"  {spec['name']}: {ts_type(spec)};")
        lines.append("}")
        lines.append("")

    lines.append("export interface ConfigurationVariant {")
    for spec in CONFIG_FIELDS:
        lines.append(f"  {spec['name']}: {ts_type(spec)};")
    lines.append("}")
    lines.append("")

    lines.append("export interface ExtractedImage {")
    lines += [
        "  file_name: string;",
        "  path: string;",
        "  url?: string;",
        "  source_file: string;",
        "  page: number;",
        "  quality?: number;",
        "}",
        "",
        "export interface PropertyImages {",
    ]
    lines += [f"  {slot}: ExtractedImage | null;" for slot in IMAGE_SLOTS]
    lines += ["}", ""]

    lines.append("export interface PropertyRecord {")
    for section in FORM:
        name = "".join(part.capitalize() for part in section.split("_"))
        lines.append(f"  {section}: {name};")
    lines.append("  configurations: ConfigurationVariant[];")
    for key in LIST_SECTIONS:
        lines.append(f"  {key}: string[];")
    lines.append("  images: PropertyImages;")
    lines.append("}")
    lines.append("")

    lines += [
        "export interface FieldMeta {",
        "  confidence: number;               // 0-1, from the model's own evidence row",
        "  source: { file: string; page: number | null };",
        "  snippet: string | null;           // verbatim text that justified the value",
        "  agreement: number;                // how many chunks/files agreed",
        "  alternatives: Array<{ value: unknown; confidence: number; source: { file: string; page: number | null } }>;",
        "}",
        "",
        "export interface Conflict {",
        "  field: string;                    // dotted path e.g. 'project_structure.total_floors'",
        "  chosen: unknown;",
        "  rejected: Array<{ value: unknown; confidence: number; source: { file: string; page: number | null } }>;",
        "}",
        "",
        "export interface ExtractionResult {",
        "  property: PropertyRecord;",
        "  form_payload: Record<string, unknown>;   // flat, keys match the form inputs 1:1",
        "  field_meta: Record<string, FieldMeta>;",
        "  conflicts: Conflict[];",
        "  needs_review: string[];           // fields under MIN_CONFIDENCE - highlight these",
        "  missing_required: string[];",
        "  image_pool: ExtractedImage[];     // everything not auto-assigned to a slot",
        "  source_files: string[];",
        "  completeness: {",
        "    fields_filled: number;",
        "    fields_total: number;",
        "    percent: number;",
        "    configurations_found: number;",
        "    amenities_found: number;",
        "  };",
        "  meta: {",
        "    files: Array<{ file: string; pages: number; scanned_pages: number; document_kind: string; seconds: number }>;",
        "    model: string;",
        "    chunks: number;",
        "    seconds: number;",
        "  };",
        "}",
        "",
    ]

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "types", "property.d.ts")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
