/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResidenceIdRouteImport } from './routes/residence.$id'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDevelopersRouteImport } from './routes/admin.developers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin.properties.index'
import { Route as DeveloperSubmissionsIdRouteImport } from './routes/developer.submissions.$id'
import { Route as DeveloperPropertiesNewRouteImport } from './routes/developer.properties.new'
import { Route as DeveloperPropertiesIdRouteImport } from './routes/developer.properties.$id'
import { Route as AdminPropertiesNewRouteImport } from './routes/admin.properties.new'
import { Route as AdminPropertiesPropertyIdRouteImport } from './routes/admin.properties.$propertyId'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenceIdRoute = ResidenceIdRouteImport.update({
  id: '/residence/$id',
  path: '/residence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevelopersRoute = AdminDevelopersRouteImport.update({
  id: '/admin/developers',
  path: '/admin/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/admin/properties/',
  path: '/admin/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSubmissionsIdRoute = DeveloperSubmissionsIdRouteImport.update({
  id: '/developer/submissions/$id',
  path: '/developer/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPropertiesNewRoute = DeveloperPropertiesNewRouteImport.update({
  id: '/developer/properties/new',
  path: '/developer/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPropertiesIdRoute = DeveloperPropertiesIdRouteImport.update({
  id: '/developer/properties/$id',
  path: '/developer/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesNewRoute = AdminPropertiesNewRouteImport.update({
  id: '/admin/properties/new',
  path: '/admin/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesPropertyIdRoute =
  AdminPropertiesPropertyIdRouteImport.update({
    id: '/admin/properties/$propertyId',
    path: '/admin/properties/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/residence/$id': typeof ResidenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/admin/properties/$propertyId': typeof AdminPropertiesPropertyIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/developer/properties/$id': typeof DeveloperPropertiesIdRoute
  '/developer/properties/new': typeof DeveloperPropertiesNewRoute
  '/developer/submissions/$id': typeof DeveloperSubmissionsIdRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/residence/$id': typeof ResidenceIdRoute
  '/admin': typeof AdminIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/admin/properties/$propertyId': typeof AdminPropertiesPropertyIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/developer/properties/$id': typeof DeveloperPropertiesIdRoute
  '/developer/properties/new': typeof DeveloperPropertiesNewRoute
  '/developer/submissions/$id': typeof DeveloperSubmissionsIdRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/residence/$id': typeof ResidenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/admin/properties/$propertyId': typeof AdminPropertiesPropertyIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/developer/properties/$id': typeof DeveloperPropertiesIdRoute
  '/developer/properties/new': typeof DeveloperPropertiesNewRoute
  '/developer/submissions/$id': typeof DeveloperSubmissionsIdRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/compare'
    | '/favorites'
    | '/admin/customers'
    | '/admin/developers'
    | '/admin/login'
    | '/admin/submissions'
    | '/residence/$id'
    | '/admin/'
    | '/developer/'
    | '/admin/properties/$propertyId'
    | '/admin/properties/new'
    | '/developer/properties/$id'
    | '/developer/properties/new'
    | '/developer/submissions/$id'
    | '/admin/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/compare'
    | '/favorites'
    | '/admin/customers'
    | '/admin/developers'
    | '/admin/login'
    | '/admin/submissions'
    | '/residence/$id'
    | '/admin'
    | '/developer'
    | '/admin/properties/$propertyId'
    | '/admin/properties/new'
    | '/developer/properties/$id'
    | '/developer/properties/new'
    | '/developer/submissions/$id'
    | '/admin/properties'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/compare'
    | '/favorites'
    | '/admin/customers'
    | '/admin/developers'
    | '/admin/login'
    | '/admin/submissions'
    | '/residence/$id'
    | '/admin/'
    | '/developer/'
    | '/admin/properties/$propertyId'
    | '/admin/properties/new'
    | '/developer/properties/$id'
    | '/developer/properties/new'
    | '/developer/submissions/$id'
    | '/admin/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDevelopersRoute: typeof AdminDevelopersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  ResidenceIdRoute: typeof ResidenceIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  AdminPropertiesPropertyIdRoute: typeof AdminPropertiesPropertyIdRoute
  AdminPropertiesNewRoute: typeof AdminPropertiesNewRoute
  DeveloperPropertiesIdRoute: typeof DeveloperPropertiesIdRoute
  DeveloperPropertiesNewRoute: typeof DeveloperPropertiesNewRoute
  DeveloperSubmissionsIdRoute: typeof DeveloperSubmissionsIdRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residence/$id': {
      id: '/residence/$id'
      path: '/residence/$id'
      fullPath: '/residence/$id'
      preLoaderRoute: typeof ResidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/developers': {
      id: '/admin/developers'
      path: '/admin/developers'
      fullPath: '/admin/developers'
      preLoaderRoute: typeof AdminDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/admin/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/submissions/$id': {
      id: '/developer/submissions/$id'
      path: '/developer/submissions/$id'
      fullPath: '/developer/submissions/$id'
      preLoaderRoute: typeof DeveloperSubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/properties/new': {
      id: '/developer/properties/new'
      path: '/developer/properties/new'
      fullPath: '/developer/properties/new'
      preLoaderRoute: typeof DeveloperPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/properties/$id': {
      id: '/developer/properties/$id'
      path: '/developer/properties/$id'
      fullPath: '/developer/properties/$id'
      preLoaderRoute: typeof DeveloperPropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties/new': {
      id: '/admin/properties/new'
      path: '/admin/properties/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AdminPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties/$propertyId': {
      id: '/admin/properties/$propertyId'
      path: '/admin/properties/$propertyId'
      fullPath: '/admin/properties/$propertyId'
      preLoaderRoute: typeof AdminPropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDevelopersRoute: AdminDevelopersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  ResidenceIdRoute: ResidenceIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  AdminPropertiesPropertyIdRoute: AdminPropertiesPropertyIdRoute,
  AdminPropertiesNewRoute: AdminPropertiesNewRoute,
  DeveloperPropertiesIdRoute: DeveloperPropertiesIdRoute,
  DeveloperPropertiesNewRoute: DeveloperPropertiesNewRoute,
  DeveloperSubmissionsIdRoute: DeveloperSubmissionsIdRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
