/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResidenceIdRouteImport } from './routes/residence.$id'
import { Route as MethodologyPropscoreRouteImport } from './routes/methodology.propscore'
import { Route as MethodologyDeveloperIntelligenceRouteImport } from './routes/methodology.developer-intelligence'
import { Route as DeveloperReviewsRouteImport } from './routes/developer.reviews'
import { Route as DeveloperEnquiriesRouteImport } from './routes/developer.enquiries'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMfaRouteImport } from './routes/admin.mfa'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDevelopersRouteImport } from './routes/admin.developers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as DeveloperIntelligenceIndexRouteImport } from './routes/developer.intelligence.index'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin.properties.index'
import { Route as DeveloperSubmissionsIdRouteImport } from './routes/developer.submissions.$id'
import { Route as DeveloperPropertiesNewRouteImport } from './routes/developer.properties.new'
import { Route as DeveloperPropertiesIdRouteImport } from './routes/developer.properties.$id'
import { Route as DeveloperIntelligencePropertyIdRouteImport } from './routes/developer.intelligence.$propertyId'
import { Route as AdminPropertiesNewRouteImport } from './routes/admin.properties.new'
import { Route as AdminPropertiesPropertyIdRouteImport } from './routes/admin.properties.$propertyId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenceIdRoute = ResidenceIdRouteImport.update({
  id: '/residence/$id',
  path: '/residence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyPropscoreRoute = MethodologyPropscoreRouteImport.update({
  id: '/methodology/propscore',
  path: '/methodology/propscore',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyDeveloperIntelligenceRoute =
  MethodologyDeveloperIntelligenceRouteImport.update({
    id: '/methodology/developer-intelligence',
    path: '/methodology/developer-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperReviewsRoute = DeveloperReviewsRouteImport.update({
  id: '/developer/reviews',
  path: '/developer/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperEnquiriesRoute = DeveloperEnquiriesRouteImport.update({
  id: '/developer/enquiries',
  path: '/developer/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/admin/mfa',
  path: '/admin/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevelopersRoute = AdminDevelopersRouteImport.update({
  id: '/admin/developers',
  path: '/admin/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIntelligenceIndexRoute =
  DeveloperIntelligenceIndexRouteImport.update({
    id: '/developer/intelligence/',
    path: '/developer/intelligence/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/admin/properties/',
  path: '/admin/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSubmissionsIdRoute = DeveloperSubmissionsIdRouteImport.update({
  id: '/developer/submissions/$id',
  path: '/developer/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPropertiesNewRoute = DeveloperPropertiesNewRouteImport.update({
  id: '/developer/properties/new',
  path: '/developer/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPropertiesIdRoute = DeveloperPropertiesIdRouteImport.update({
  id: '/developer/properties/$id',
  path: '/developer/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIntelligencePropertyIdRoute =
  DeveloperIntelligencePropertyIdRouteImport.update({
    id: '/developer/intelligence/$propertyId',
    path: '/developer/intelligence/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPropertiesNewRoute = AdminPropertiesNewRouteImport.update({
  id: '/admin/properties/new',
  path: '/admin/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesPropertyIdRoute =
  AdminPropertiesPropertyIdRouteImport.update({
    id: '/admin/properties/$propertyId',
    path: '/admin/properties/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/developer/enquiries': typeof DeveloperEnquiriesRoute
  '/developer/reviews': typeof DeveloperReviewsRoute
  '/methodology/developer-intelligence': typeof MethodologyDeveloperIntelligenceRoute
  '/methodology/propscore': typeof MethodologyPropscoreRoute
  '/residence/$id': typeof ResidenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/admin/properties/$propertyId': typeof AdminPropertiesPropertyIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/developer/intelligence/$propertyId': typeof DeveloperIntelligencePropertyIdRoute
  '/developer/properties/$id': typeof DeveloperPropertiesIdRoute
  '/developer/properties/new': typeof DeveloperPropertiesNewRoute
  '/developer/submissions/$id': typeof DeveloperSubmissionsIdRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/developer/intelligence/': typeof DeveloperIntelligenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/developer/enquiries': typeof DeveloperEnquiriesRoute
  '/developer/reviews': typeof DeveloperReviewsRoute
  '/methodology/developer-intelligence': typeof MethodologyDeveloperIntelligenceRoute
  '/methodology/propscore': typeof MethodologyPropscoreRoute
  '/residence/$id': typeof ResidenceIdRoute
  '/admin': typeof AdminIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/admin/properties/$propertyId': typeof AdminPropertiesPropertyIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/developer/intelligence/$propertyId': typeof DeveloperIntelligencePropertyIdRoute
  '/developer/properties/$id': typeof DeveloperPropertiesIdRoute
  '/developer/properties/new': typeof DeveloperPropertiesNewRoute
  '/developer/submissions/$id': typeof DeveloperSubmissionsIdRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
  '/developer/intelligence': typeof DeveloperIntelligenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/developer/enquiries': typeof DeveloperEnquiriesRoute
  '/developer/reviews': typeof DeveloperReviewsRoute
  '/methodology/developer-intelligence': typeof MethodologyDeveloperIntelligenceRoute
  '/methodology/propscore': typeof MethodologyPropscoreRoute
  '/residence/$id': typeof ResidenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/admin/properties/$propertyId': typeof AdminPropertiesPropertyIdRoute
  '/admin/properties/new': typeof AdminPropertiesNewRoute
  '/developer/intelligence/$propertyId': typeof DeveloperIntelligencePropertyIdRoute
  '/developer/properties/$id': typeof DeveloperPropertiesIdRoute
  '/developer/properties/new': typeof DeveloperPropertiesNewRoute
  '/developer/submissions/$id': typeof DeveloperSubmissionsIdRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/developer/intelligence/': typeof DeveloperIntelligenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/community-guidelines'
    | '/compare'
    | '/favorites'
    | '/privacy'
    | '/terms'
    | '/admin/customers'
    | '/admin/developers'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/moderation'
    | '/admin/submissions'
    | '/admin/verification'
    | '/developer/enquiries'
    | '/developer/reviews'
    | '/methodology/developer-intelligence'
    | '/methodology/propscore'
    | '/residence/$id'
    | '/admin/'
    | '/developer/'
    | '/admin/properties/$propertyId'
    | '/admin/properties/new'
    | '/developer/intelligence/$propertyId'
    | '/developer/properties/$id'
    | '/developer/properties/new'
    | '/developer/submissions/$id'
    | '/admin/properties/'
    | '/developer/intelligence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/community-guidelines'
    | '/compare'
    | '/favorites'
    | '/privacy'
    | '/terms'
    | '/admin/customers'
    | '/admin/developers'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/moderation'
    | '/admin/submissions'
    | '/admin/verification'
    | '/developer/enquiries'
    | '/developer/reviews'
    | '/methodology/developer-intelligence'
    | '/methodology/propscore'
    | '/residence/$id'
    | '/admin'
    | '/developer'
    | '/admin/properties/$propertyId'
    | '/admin/properties/new'
    | '/developer/intelligence/$propertyId'
    | '/developer/properties/$id'
    | '/developer/properties/new'
    | '/developer/submissions/$id'
    | '/admin/properties'
    | '/developer/intelligence'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/community-guidelines'
    | '/compare'
    | '/favorites'
    | '/privacy'
    | '/terms'
    | '/admin/customers'
    | '/admin/developers'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/moderation'
    | '/admin/submissions'
    | '/admin/verification'
    | '/developer/enquiries'
    | '/developer/reviews'
    | '/methodology/developer-intelligence'
    | '/methodology/propscore'
    | '/residence/$id'
    | '/admin/'
    | '/developer/'
    | '/admin/properties/$propertyId'
    | '/admin/properties/new'
    | '/developer/intelligence/$propertyId'
    | '/developer/properties/$id'
    | '/developer/properties/new'
    | '/developer/submissions/$id'
    | '/admin/properties/'
    | '/developer/intelligence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDevelopersRoute: typeof AdminDevelopersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMfaRoute: typeof AdminMfaRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  DeveloperEnquiriesRoute: typeof DeveloperEnquiriesRoute
  DeveloperReviewsRoute: typeof DeveloperReviewsRoute
  MethodologyDeveloperIntelligenceRoute: typeof MethodologyDeveloperIntelligenceRoute
  MethodologyPropscoreRoute: typeof MethodologyPropscoreRoute
  ResidenceIdRoute: typeof ResidenceIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  AdminPropertiesPropertyIdRoute: typeof AdminPropertiesPropertyIdRoute
  AdminPropertiesNewRoute: typeof AdminPropertiesNewRoute
  DeveloperIntelligencePropertyIdRoute: typeof DeveloperIntelligencePropertyIdRoute
  DeveloperPropertiesIdRoute: typeof DeveloperPropertiesIdRoute
  DeveloperPropertiesNewRoute: typeof DeveloperPropertiesNewRoute
  DeveloperSubmissionsIdRoute: typeof DeveloperSubmissionsIdRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
  DeveloperIntelligenceIndexRoute: typeof DeveloperIntelligenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residence/$id': {
      id: '/residence/$id'
      path: '/residence/$id'
      fullPath: '/residence/$id'
      preLoaderRoute: typeof ResidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology/propscore': {
      id: '/methodology/propscore'
      path: '/methodology/propscore'
      fullPath: '/methodology/propscore'
      preLoaderRoute: typeof MethodologyPropscoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology/developer-intelligence': {
      id: '/methodology/developer-intelligence'
      path: '/methodology/developer-intelligence'
      fullPath: '/methodology/developer-intelligence'
      preLoaderRoute: typeof MethodologyDeveloperIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/reviews': {
      id: '/developer/reviews'
      path: '/developer/reviews'
      fullPath: '/developer/reviews'
      preLoaderRoute: typeof DeveloperReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/enquiries': {
      id: '/developer/enquiries'
      path: '/developer/enquiries'
      fullPath: '/developer/enquiries'
      preLoaderRoute: typeof DeveloperEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mfa': {
      id: '/admin/mfa'
      path: '/admin/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/developers': {
      id: '/admin/developers'
      path: '/admin/developers'
      fullPath: '/admin/developers'
      preLoaderRoute: typeof AdminDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/intelligence/': {
      id: '/developer/intelligence/'
      path: '/developer/intelligence'
      fullPath: '/developer/intelligence/'
      preLoaderRoute: typeof DeveloperIntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/admin/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/submissions/$id': {
      id: '/developer/submissions/$id'
      path: '/developer/submissions/$id'
      fullPath: '/developer/submissions/$id'
      preLoaderRoute: typeof DeveloperSubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/properties/new': {
      id: '/developer/properties/new'
      path: '/developer/properties/new'
      fullPath: '/developer/properties/new'
      preLoaderRoute: typeof DeveloperPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/properties/$id': {
      id: '/developer/properties/$id'
      path: '/developer/properties/$id'
      fullPath: '/developer/properties/$id'
      preLoaderRoute: typeof DeveloperPropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/intelligence/$propertyId': {
      id: '/developer/intelligence/$propertyId'
      path: '/developer/intelligence/$propertyId'
      fullPath: '/developer/intelligence/$propertyId'
      preLoaderRoute: typeof DeveloperIntelligencePropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties/new': {
      id: '/admin/properties/new'
      path: '/admin/properties/new'
      fullPath: '/admin/properties/new'
      preLoaderRoute: typeof AdminPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties/$propertyId': {
      id: '/admin/properties/$propertyId'
      path: '/admin/properties/$propertyId'
      fullPath: '/admin/properties/$propertyId'
      preLoaderRoute: typeof AdminPropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDevelopersRoute: AdminDevelopersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMfaRoute: AdminMfaRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  DeveloperEnquiriesRoute: DeveloperEnquiriesRoute,
  DeveloperReviewsRoute: DeveloperReviewsRoute,
  MethodologyDeveloperIntelligenceRoute: MethodologyDeveloperIntelligenceRoute,
  MethodologyPropscoreRoute: MethodologyPropscoreRoute,
  ResidenceIdRoute: ResidenceIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  AdminPropertiesPropertyIdRoute: AdminPropertiesPropertyIdRoute,
  AdminPropertiesNewRoute: AdminPropertiesNewRoute,
  DeveloperIntelligencePropertyIdRoute: DeveloperIntelligencePropertyIdRoute,
  DeveloperPropertiesIdRoute: DeveloperPropertiesIdRoute,
  DeveloperPropertiesNewRoute: DeveloperPropertiesNewRoute,
  DeveloperSubmissionsIdRoute: DeveloperSubmissionsIdRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
  DeveloperIntelligenceIndexRoute: DeveloperIntelligenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
