// Hand-maintained (NOT auto-generated). Composes the generated requireSupabaseAuth
// middleware with an admin_profiles role gate. Do not fold this into
// auth-middleware.ts — that file is regenerated by the Supabase integration.
import { createMiddleware } from "@tanstack/react-start";
import { requireSupabaseAuth } from "./auth-middleware";

export interface AdminProfileContext {
  id: string;
  role: "owner" | "reviewer" | "support" | "developer";
  email: string;
  isActive: boolean;
}

// Any active admin (owner OR developer). Injects context.adminProfile.
export const requireAdminAuth = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ next, context }) => {
    const { supabaseAdmin } = await import("./client.server");
    const { data, error } = await supabaseAdmin
      .from("admin_profiles")
      .select("id, role, email, is_active")
      .eq("id", context.userId)
      .maybeSingle();
    if (error || !data || !data.is_active) {
      throw new Error("Unauthorized: not an active admin");
    }
    if (!["owner", "reviewer", "support", "developer"].includes(data.role)) {
      throw new Error("Unauthorized: invalid role");
    }
    const adminProfile: AdminProfileContext = {
      id: data.id,
      role: data.role as AdminProfileContext["role"],
      email: data.email,
      isActive: data.is_active,
    };
    return next({ context: { adminProfile } });
  });

// Owner only. Layers on top of requireAdminAuth.
export const requireOwnerAuth = createMiddleware({ type: "function" })
  .middleware([requireAdminAuth])
  .server(async ({ next, context }) => {
    if (context.adminProfile.role !== "owner") {
      throw new Error("Forbidden: owner access required");
    }
    return next();
  });

export const requireReviewerAuth = createMiddleware({ type: "function" })
  .middleware([requireAdminAuth])
  .server(async ({ next, context }) => {
    if (context.adminProfile.role !== "owner" && context.adminProfile.role !== "reviewer") {
      throw new Error("Forbidden: reviewer access required");
    }
    return next();
  });

export const requireDeveloperAuth = createMiddleware({ type: "function" })
  .middleware([requireAdminAuth])
  .server(async ({ next, context }) => {
    if (context.adminProfile.role !== "developer") {
      throw new Error("Forbidden: developer access required");
    }
    return next();
  });

export const requireModerationAuth = createMiddleware({ type: "function" })
  .middleware([requireAdminAuth])
  .server(async ({ next, context }) => {
    if (!(["owner", "reviewer", "support"] as const).includes(context.adminProfile.role as never)) {
      throw new Error("Forbidden: moderation access required");
    }
    return next();
  });
